//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project___Web_Services___Client.SmoothieService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmoothieService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name fas from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponse HelloWorld(Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponse> HelloWorldAsync(Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name fruitsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fruits", ReplyAction="*")]
        Mini_Project___Web_Services___Client.SmoothieService.fruitsResponse fruits(Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fruits", ReplyAction="*")]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.fruitsResponse> fruitsAsync(Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest request);
        
        // CODEGEN: Generating message contract since element name fruit1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/canMake", ReplyAction="*")]
        Mini_Project___Web_Services___Client.SmoothieService.canMakeResponse canMake(Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/canMake", ReplyAction="*")]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.canMakeResponse> canMakeAsync(Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest request);
        
        // CODEGEN: Generating message contract since element name fruit1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/explore", ReplyAction="*")]
        Mini_Project___Web_Services___Client.SmoothieService.exploreResponse explore(Mini_Project___Web_Services___Client.SmoothieService.exploreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/explore", ReplyAction="*")]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.exploreResponse> exploreAsync(Mini_Project___Web_Services___Client.SmoothieService.exploreRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipie", ReplyAction="*")]
        Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponse getRecipie(Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecipie", ReplyAction="*")]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponse> getRecipieAsync(Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fas;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string fas) {
            this.fas = fas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fruitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fruits", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.fruitsRequestBody Body;
        
        public fruitsRequest() {
        }
        
        public fruitsRequest(Mini_Project___Web_Services___Client.SmoothieService.fruitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fruitsRequestBody {
        
        public fruitsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fruitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fruitsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.fruitsResponseBody Body;
        
        public fruitsResponse() {
        }
        
        public fruitsResponse(Mini_Project___Web_Services___Client.SmoothieService.fruitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fruitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.ArrayOfString fruitsResult;
        
        public fruitsResponseBody() {
        }
        
        public fruitsResponseBody(Mini_Project___Web_Services___Client.SmoothieService.ArrayOfString fruitsResult) {
            this.fruitsResult = fruitsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class canMakeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="canMake", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.canMakeRequestBody Body;
        
        public canMakeRequest() {
        }
        
        public canMakeRequest(Mini_Project___Web_Services___Client.SmoothieService.canMakeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class canMakeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruit1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fruit2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool iceOrNot;
        
        public canMakeRequestBody() {
        }
        
        public canMakeRequestBody(string fruit1, string fruit2, bool iceOrNot) {
            this.fruit1 = fruit1;
            this.fruit2 = fruit2;
            this.iceOrNot = iceOrNot;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class canMakeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="canMakeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.canMakeResponseBody Body;
        
        public canMakeResponse() {
        }
        
        public canMakeResponse(Mini_Project___Web_Services___Client.SmoothieService.canMakeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class canMakeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string canMakeResult;
        
        public canMakeResponseBody() {
        }
        
        public canMakeResponseBody(string canMakeResult) {
            this.canMakeResult = canMakeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exploreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="explore", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.exploreRequestBody Body;
        
        public exploreRequest() {
        }
        
        public exploreRequest(Mini_Project___Web_Services___Client.SmoothieService.exploreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class exploreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruit1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fruit2;
        
        public exploreRequestBody() {
        }
        
        public exploreRequestBody(string fruit1, string fruit2) {
            this.fruit1 = fruit1;
            this.fruit2 = fruit2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class exploreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exploreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.exploreResponseBody Body;
        
        public exploreResponse() {
        }
        
        public exploreResponse(Mini_Project___Web_Services___Client.SmoothieService.exploreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class exploreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.ArrayOfString exploreResult;
        
        public exploreResponseBody() {
        }
        
        public exploreResponseBody(Mini_Project___Web_Services___Client.SmoothieService.ArrayOfString exploreResult) {
            this.exploreResult = exploreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipie", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequestBody Body;
        
        public getRecipieRequest() {
        }
        
        public getRecipieRequest(Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getRecipieRequestBody() {
        }
        
        public getRecipieRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponseBody Body;
        
        public getRecipieResponse() {
        }
        
        public getRecipieResponse(Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRecipieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRecipieResult;
        
        public getRecipieResponseBody() {
        }
        
        public getRecipieResponseBody(string getRecipieResult) {
            this.getRecipieResult = getRecipieResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap>, Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponse Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.HelloWorld(Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string fas) {
            Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequestBody();
            inValue.Body.fas = fas;
            Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponse retVal = ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponse> Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.HelloWorldAsync(Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.HelloWorldResponse> HelloWorldAsync(string fas) {
            Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.HelloWorldRequestBody();
            inValue.Body.fas = fas;
            return ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mini_Project___Web_Services___Client.SmoothieService.fruitsResponse Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.fruits(Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest request) {
            return base.Channel.fruits(request);
        }
        
        public Mini_Project___Web_Services___Client.SmoothieService.ArrayOfString fruits() {
            Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.fruitsRequestBody();
            Mini_Project___Web_Services___Client.SmoothieService.fruitsResponse retVal = ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).fruits(inValue);
            return retVal.Body.fruitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.fruitsResponse> Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.fruitsAsync(Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest request) {
            return base.Channel.fruitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.fruitsResponse> fruitsAsync() {
            Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.fruitsRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.fruitsRequestBody();
            return ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).fruitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mini_Project___Web_Services___Client.SmoothieService.canMakeResponse Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.canMake(Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest request) {
            return base.Channel.canMake(request);
        }
        
        public string canMake(string fruit1, string fruit2, bool iceOrNot) {
            Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.canMakeRequestBody();
            inValue.Body.fruit1 = fruit1;
            inValue.Body.fruit2 = fruit2;
            inValue.Body.iceOrNot = iceOrNot;
            Mini_Project___Web_Services___Client.SmoothieService.canMakeResponse retVal = ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).canMake(inValue);
            return retVal.Body.canMakeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.canMakeResponse> Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.canMakeAsync(Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest request) {
            return base.Channel.canMakeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.canMakeResponse> canMakeAsync(string fruit1, string fruit2, bool iceOrNot) {
            Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.canMakeRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.canMakeRequestBody();
            inValue.Body.fruit1 = fruit1;
            inValue.Body.fruit2 = fruit2;
            inValue.Body.iceOrNot = iceOrNot;
            return ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).canMakeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mini_Project___Web_Services___Client.SmoothieService.exploreResponse Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.explore(Mini_Project___Web_Services___Client.SmoothieService.exploreRequest request) {
            return base.Channel.explore(request);
        }
        
        public Mini_Project___Web_Services___Client.SmoothieService.ArrayOfString explore(string fruit1, string fruit2) {
            Mini_Project___Web_Services___Client.SmoothieService.exploreRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.exploreRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.exploreRequestBody();
            inValue.Body.fruit1 = fruit1;
            inValue.Body.fruit2 = fruit2;
            Mini_Project___Web_Services___Client.SmoothieService.exploreResponse retVal = ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).explore(inValue);
            return retVal.Body.exploreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.exploreResponse> Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.exploreAsync(Mini_Project___Web_Services___Client.SmoothieService.exploreRequest request) {
            return base.Channel.exploreAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.exploreResponse> exploreAsync(string fruit1, string fruit2) {
            Mini_Project___Web_Services___Client.SmoothieService.exploreRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.exploreRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.exploreRequestBody();
            inValue.Body.fruit1 = fruit1;
            inValue.Body.fruit2 = fruit2;
            return ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).exploreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponse Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.getRecipie(Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest request) {
            return base.Channel.getRecipie(request);
        }
        
        public string getRecipie(string name) {
            Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequestBody();
            inValue.Body.name = name;
            Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponse retVal = ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).getRecipie(inValue);
            return retVal.Body.getRecipieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponse> Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap.getRecipieAsync(Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest request) {
            return base.Channel.getRecipieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mini_Project___Web_Services___Client.SmoothieService.getRecipieResponse> getRecipieAsync(string name) {
            Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest inValue = new Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequest();
            inValue.Body = new Mini_Project___Web_Services___Client.SmoothieService.getRecipieRequestBody();
            inValue.Body.name = name;
            return ((Mini_Project___Web_Services___Client.SmoothieService.WebService1Soap)(this)).getRecipieAsync(inValue);
        }
    }
}
